apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: 10.101.164.228
  POSTGRES_PORT: "5432"
  POSTGRES_NAME: tododb
